<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MovieStreaming.Domain\MovieStreaming.Domain.csproj" />
    <ProjectReference Include="..\MovieStreaming.Infrastructure\MovieStreaming.Infrastructure.csproj" />
  </ItemGroup>

</Project>
